# Generated by Django 3.2.7 on 2021-09-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('number_pages', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
