# Generated by Django 3.2.7 on 2021-09-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210922_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'информация о клиенте', 'verbose_name_plural': 'информация о клиенте'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'заказ принят', 'verbose_name_plural': 'заказы приняты'},
        ),
    ]
